services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Kmi\Typo3NaturalLanguageQuery\:
        resource: '../Classes/*'
        exclude: '../Classes/Domain/Model/*'

    Kmi\Typo3NaturalLanguageQuery\Command\QueryCommand:
        tags:
            -   name: console.command
                command: 'nlq:ask'
                description: 'Ask a natural language question for querying database records.'

    Kmi\Typo3NaturalLanguageQuery\Service\PromptGenerator:
        public: true
