services:
    web:
        environment:
            - EXTENSION_KEY=typo3_natural_language_query
            - EXTENSION_NAME=typo3-natural-language-query
            - PACKAGE_NAME=konradmichalik/typo3-natural-language-query
            - TYPO3_VERSIONS=13

            # TYPO3 v11 and v12 config
            - TYPO3_INSTALL_DB_DRIVER=mysqli
            - TYPO3_INSTALL_DB_USER=root
            - TYPO3_INSTALL_DB_PASSWORD=root
            - TYPO3_INSTALL_DB_HOST=db
            - TYPO3_INSTALL_DB_UNIX_SOCKET=
            - TYPO3_INSTALL_DB_USE_EXISTING=0
            - TYPO3_INSTALL_ADMIN_USER=admin
            - TYPO3_INSTALL_ADMIN_PASSWORD=Password1!
            - TYPO3_INSTALL_SITE_NAME=EXT:typo3-natural-language-query Dev Environment
            - TYPO3_INSTALL_SITE_SETUP_TYPE=site
            - TYPO3_INSTALL_WEB_SERVER_CONFIG=apache

            # TYPO3 v13 config
            - TYPO3_DB_DRIVER=mysqli
            - TYPO3_DB_USERNAME=root
            - TYPO3_DB_PASSWORD=root
            - TYPO3_DB_HOST=db
            - TYPO3_SETUP_ADMIN_EMAIL=admin@example.com
            - TYPO3_SETUP_ADMIN_USERNAME=admin
            - TYPO3_SETUP_ADMIN_PASSWORD=Password1!
            - TYPO3_PROJECT_NAME=EXT:typo3-natural-language-query Dev Environment
            - TYPO3_SERVER_TYPE=apache
